/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [28.34KB] > \public\assets\models\attacus_attlas_butterfly__moth\scene-transformed.glb [122.97KB] (-334%)
Author: Erina eka syaharani (https://sketchfab.com/erinaekasyaharani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/attacus-attlas-butterfly-moth-1f7d0337798b499ebc020d65d3f26e01
Title: Attacus Attlas, butterfly , moth
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AttacusAtlasButterfly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/models/attacus_attlas_butterfly__moth/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // console.log(actions);
    actions['Take 01'].timeScale = 0.78;
    actions['Take 01'].play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Root" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Mesh016" position={[0, 0.133, 2.063]} rotation={[0, 0, 0]} scale={0.016}>
            <group name="Mesh026" position={[-4.937, -3.428, 7.224]}>
              <mesh name="Mesh026_0" geometry={nodes.Mesh026_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh023">
              <mesh name="Mesh023_0" geometry={nodes.Mesh023_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh020">
              <mesh name="Mesh020_0" geometry={nodes.Mesh020_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh017">
              <mesh name="Mesh017_0" geometry={nodes.Mesh017_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh008" position={[-0.008, 4.677, -8.846]} rotation={[-0.528, 0, 0]}>
              <mesh name="Mesh008_0" geometry={nodes.Mesh008_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh014" position={[8.261, 4.701, 1.217]} rotation={[0, 0, -0.914]}>
              <mesh name="Mesh014_0" geometry={nodes.Mesh014_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh013" position={[-8.393, 4.701, 1.538]} rotation={[0, 0, 0.884]}>
              <mesh name="Mesh013_0" geometry={nodes.Mesh013_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh005">
              <mesh name="Mesh005_0" geometry={nodes.Mesh005_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh002">
              <mesh name="Mesh002_0" geometry={nodes.Mesh002_0.geometry} material={materials.mat1} />
            </group>
            <mesh name="Mesh016_0" geometry={nodes.Mesh016_0.geometry} material={materials.mat1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/attacus_attlas_butterfly__moth/scene-transformed.glb')
