/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [11.99KB] > \public\assets\models\blue_butterfly\scene-transformed.glb [110.5KB] (-822%)
Author: Erina eka syaharani (https://sketchfab.com/erinaekasyaharani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-butterfly-4fe9c2835522458a822b5b784a680de4
Title: blue butterfly
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BlueButterfly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/models/blue_butterfly/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // console.log(actions);
    actions['Take 01'].timeScale = 0.5;
    actions['Take 01'].play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Root" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Mesh009" rotation={[0, 0, 0]} scale={0.005}>
            <group name="Mesh013" rotation={[0.009, -0.016, -1.049]}>
              <mesh name="Mesh013_0" geometry={nodes.Mesh013_0.geometry} material={materials.mat1} />
            </group>
            <group name="Mesh" rotation={[0.01, 0.015, 0.984]}>
              <mesh name="Mesh_0" geometry={nodes.Mesh_0.geometry} material={materials.mat1} />
            </group>
            <mesh name="Mesh009_0" geometry={nodes.Mesh009_0.geometry} material={materials.mat1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/blue_butterfly/scene-transformed.glb')
